# Generated by Django 3.2.8 on 2021-10-21 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('answer', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('FullStack', 'FullStack')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
