# Generated by Django 3.2.8 on 2021-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('FullStack', 'fullStack'), ('Backend', 'backend'), ('Frontend', 'frontend')], max_length=200),
        ),
    ]
