# Generated by Django 3.2.8 on 2021-10-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
