# Generated by Django 3.2.8 on 2021-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Backend', 'backend'), ('Frontend', 'frontend'), ('FullStack', 'fullStack')], max_length=200),
        ),
    ]
