name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3

      - name: Say Hi to Mark
        run: echo "Hello Mark"

      - name: Install python version 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      
      - id: cache-pipenv
        uses: actions/cache@v2
        with: 
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      

      - name: Install all dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: | 
          pipenv install --deploy --dev

      - name: Listing requirements
        run: pip freeze 
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production

    steps:
      - name: pulling git repo
        uses: actions/checkout@v3

      - name: Deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}