name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3

      - name: Say Hi to Mark
        run: echo "Hello Mark"

      - name: Install python version 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install all dependencies
        run: | 
          pipenv install --deploy --dev

      - name: Listing requirements
        run: pip freeze 
  
 